### ISSUE TITLE
OLED not working

### ISSUE THREAD

**Issue by cg089** [zpukr/ArduRower#2]
Hi,
thanks for this project!

Does anyone have idea why the OLED screen is not working?
I bought the "Heletec WiFi Kit 32" which is used by this project. The OLED is also an SSD1306 0x3c on SDA    4, SCL   15, RST 16. I tried flashing ESPHome, OLED works perfect. Flashing ArduRower, it stays dark.

Thanks for any hint.

**Comment by cg089** [comment]
After flashing bin file instead of compiled src the oled works.

**Comment by aehs** [comment]
the same issue here with the same board, any ideas?

**Comment by zpukr** [comment]
> the same issue here with the same board, any ideas?

It's very difficult for me to say why this is happening. Most likely, there have been changes in the libraries, and the project has not been developed for a very long time. You can try to use PlatformIO_fullpack.rar, it includes all the libraries that were relevant at the time.
