### ISSUE TITLE
Garmin Instinct 2

### ISSUE THREAD

**Issue by Hascii26** [zpukr/ArduRower#4]
Hi @zpukr,

is it possible to make the Garmin App compatible to the Instinct 2?

Thank you

**Comment by zpukr** [comment]
done
1.2.5 Add support of Instinct 2

**Comment by Hascii26** [comment]
Thank you very much, but I can't find it in the IQ store over Garmin Connect. The list of compatible devices says, that the Instinct is not compatible. I'm from Germany, don't know if that's the problem.

**Comment by zpukr** [comment]
hm... App v1.2.5 has been 'pending' for 3 days now, when it usually took minutes. I will try ask Garmin Connect support to solve this problem
