### ISSUE TITLE
Update Garmin App?

### ISSUE THREAD

**Issue by patrickstigler** [zpukr/ArduRower#8]
Hi, 
I really like your project. And used it for a while with my Instinct 2. But since I just upgraded to the Enduro 3, I can't use it right now.
Could you add Enduro 3 support to the garmin app, please? 
That would be awesome. Thanks.

**Comment by zpukr** [comment]
Done. Download v1.3.3 from Connect IQ store

**Comment by patrickstigler** [comment]
Thank you, very much
